# Site settings
name: 无嘴小呆子
email: ljd2038@gmail.com
author: 李江东
url: http://lijiangdong.github.io
resume_site:
github: https://github.com/lijiangdong/
baseurl: ""
description: 用代码书写这个世界!
meta_description: 李江东;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lijiangdong
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light


gems: [jekyll-paginate]
paginate: 5