# Site settings
title: 李江东
description: '用代码书写这个世界。'
#url: 'http://127.0.0.1:4000/'
url: 'http://lijiangdong.com/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '李江东'
  email: ljd2038@gmail.com
  twitter_username: lijiangdong
  facebook_username: lijiangdong
  github_username:  lijiangdong
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
